/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codurance.fizzbuzz;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class FizzBuzzShould {

    @Test
    void convert_1_to_1() {
        assertEquals("1", new FizzBuzz().convert(1));
    }
}
