/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codurance.fizzbuzz;

public class FizzBuzz {

    public String convert(int i) {
        throw new UnsupportedOperationException("implement me!");
    }
}
